---
- name: Set up system as desktop host
  hosts: fedora-desktop-hosts
  gather_facts: yes
  vars:
    myhostame: fedora.local
  #vars_files:
  #  - /root/vars.yml
  #
  #  ansible-role-ssh
  #  ansible-role-update-packages
  #  reboot
  #
  tasks:
    - name: Make sure that an empty requirements.yml file exists
      file:
        path: requirements.yml
        state: touch

    - name: Create requirements.yml
      blockinfile:
        path: requirements.yml
        create: yes
        block: |
          # Install a role from the Ansible Galaxy
          #- src: joschro.rpmfusion
          #- src: joschro.rpmfusion-tainted
          #- src: joschro.libvirtd
          #- src: joschro.cockpit

          # Install a role from GitHub
          - src: https://github.com/joschro/ansible-role-rpmfusion
            name: joschro.rpmfusion
              #- src: https://github.com/joschro/ansible-role-rpmfusion-tainted
              #  name: joschro.rpmfusion-tainted
          - src: https://github.com/joschro/ansible-role-libvirtd
            name: joschro.libvirtd
          - src: https://github.com/joschro/ansible-role-cockpit
            name: joschro.cockpit

    - name: Install required packages
      become: yes
      package:
        name:
          - "*-firmware"
          - ansible
          - git
        state: present

    - name: Source required roles
      command: ansible-galaxy install -r requirements.yml
      # (add parameter --force to update role on succeeding runs of playbook)

    - name: Make sure that an empty requirements.yml file exists
      file:
        path: ansible-playbook-fedora-desktop-host.yml
        state: touch

    - name: Create ansible-playbook-fedora-desktop-host.yml
      blockinfile:
        path: ansible-playbook-fedora-desktop-host.yml
        create: yes
        block: |
          ---
          # Install a role from the Ansible Galaxy
          - name: Execute local playbook
            hosts: localhost
            tasks:
              - name: Execute rpmfusion role
                include_role:
                  name: joschro.rpmfusion
              - name: Execute libvirtd role
                include_role:
                  name: joschro.libvirtd
              - name: Execute cockpit role
                include_role:
                  name: joschro.cockpit
              - name: Add current IP to motd
                lineinfile:
                  path: /etc/issue
                  regexp: '^IP address:  '
                  insertafter: '^ '
                  line: 'IP address: \4'
              - name: Update packages
                package:
                  name: '*'
                  state: latest

    - name: Add user to sudoers to run ansible-playbook without password
      become: yes
      lineinfile:
        path: /etc/sudoers
        line: "{{ ansible_user_id }} localhost=/usr/bin/ansible-playbook ansible-playbook-fedora-desktop-host.yml"
        create: yes

    - name: Execute ansible-playbook-fedora-desktop-host.yml
      command: sudo ansible-playbook ansible-playbook-fedora-desktop-host.yml
      register: result

    - name: Report playbook results
      debug:
        var: result
        verbosity: 2

        #    - name: Enable SSH service
        #      become: yes
        #      service:
        #        name: sshd
        #        state: started
        #        enabled: yes
