---
- hosts: fedora-desktop-hosts
  become: yes
  gather_facts: yes
  vars:
    myhostame: fedora.local
  #vars_files:
  #  - /root/vars.yml
  #
  #  ansible-role-RPMfusion
  #  ansible-role-RPMfusion-tainted
  #  ansible-role-libvirt
  #  ansible-role-cockpit
  #  ansible-role-ssh
  #  ansible-role-update-packages
  #  reboot
  #
  tasks:
    - name: Install RPMfusion repositories
      command: dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      args:
        creates: /etc/yum.repos.d/rpmfusion-free.repo
        removes: /etc/fedora-release

    - name: Install AppStream metadata
      command: dnf groupupdate core -y

    - name: Install tainted repositories
      package:
        name:
          - rpmfusion-free-release-tainted
          - rpmfusion-nonfree-release-tainted
        state: present

    - name: Install packages
      package:
        name:
          - "*-firmware"
          - "@virtualization"
          - ansible
          - cockpit
          - cockpit-composer
          - cockpit-machines
          - cockpit-navigator
          - cockpit-networkmanager
          - cockpit-podman
          - cockpit-session-recording
          - cockpit-storaged
          - cockpit-system
          - virt-top
          - podman
        state: present

    - name: Force systemd to reread config, enable and start service libvirtd
      systemd:
        name: libvirtd
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Force systemd to reread config, enable and start service cockpit.socket
      systemd:
        name: cockpit.socket
        state: restarted
        daemon_reload: yes
        enabled: yes
    
    - name: Add current IP to motd
      lineinfile:
          path: /etc/issue
          regexp: '^IP address:  '
          insertafter: '^ '
          line: 'IP address: \4'
        
    - name: Enable SSH service
      become: yes
      service:
        name: sshd
        state: started
        enabled: yes
    
    - name: Update packages
      package:
        name: '*'
        state: latest
