---
- name: Set up system as desktop host
  hosts: fedora-desktop-hosts
  gather_facts: yes
  vars:
    myhostame: fedora.local
  #vars_files:
  #  - /root/vars.yml
  #
  #  ansible-role-libvirt
  #  ansible-role-cockpit
  #  ansible-role-ssh
  #  ansible-role-update-packages
  #  reboot
  #
  tasks:
    - name: Make sure that an empty requirements.yml file exists
      file:
        path: requirements.yml
        state: touch

    - name: Create requirements.yml
      blockinfile:
        path: requirements.yml
        create: yes
        block: |
          # Install a role from the Ansible Galaxy
          #- src: joschro.rpmfusion
          #- src: joschro.rpmfusion-tainted
          #- src: joschro.libvirtd
          #- src: joschro.cockpit

          # Install a role from GitHub
          - src: https://github.com/joschro/ansible-role-rpmfusion
            name: joschro.rpmfusion
              #- src: https://github.com/joschro/ansible-role-rpmfusion-tainted
              #  name: joschro.rpmfusion-tainted
          - src: https://github.com/joschro/ansible-role-libvirtd
            name: joschro.libvirtd
          - src: https://github.com/joschro/ansible-role-cockpit
            name: joschro.cockpit

    - name: Install required packages
      become: yes
      package:
        name: git
        state: present

    - name: Source required roles
      command: ansible-galaxy install -r requirements.yml
      # (add parameter --force to update role on succeeding runs of playbook)

    - name: Execute rpmfusion role
      include_role:
        name: joschro.rpmfusion

    - name: Execute libvirtd role
      include_role:
        name: joschro.libvirtd

    - name: Execute cockpit role
      include_role:
        name: joschro.cockpit


    - name: Install packages
      package:
        name:
          - "*-firmware"
          - ansible
          - virt-top
          - podman
        state: present

    - name: Add current IP to motd
      lineinfile:
          path: /etc/issue
          regexp: '^IP address:  '
          insertafter: '^ '
          line: 'IP address: \4'
        
    - name: Enable SSH service
      become: yes
      service:
        name: sshd
        state: started
        enabled: yes
    
    - name: Update packages
      package:
        name: '*'
        state: latest
