---
- hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    myhostame: myfedora.local
  #vars_files:
  #  - /root/vars.yml
  tasks:
    - name: Install RPMfusion repositories
      shell: dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      args:
        creates: /etc/yum.repos.d/rpmfusion-free.repo
        removes: /etc/fedora-release

    - name: Install AppStream metadata
      shell: dnf groupupdate core -y

    - name: Install tainted repositories
      package:
        name:
          - rpmfusion-free-release-tainted
          - rpmfusion-nonfree-release-tainted
        state: present

    - name: Install packages
      package:
        name:
          - vim
          - tmux
          - podman
          - cockpit
          - cockpit-composer
          - cockpit-machines
          - cockpit-navigator
          - cockpit-networkmanager
          - cockpit-podman
          - cockpit-session-recording
          - cockpit-storaged
          - cockpit-system
          - libreoffice
          - ImageMagick
          - bash-completion
          - libdvdcss
          - digikam
          - "*-firmware"
          - "@virtualization"
          - virt-top
        state: present

    - name: Force systemd to reread config, enable and start service libvirtd
      systemd:
        name: libvirtd
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Force systemd to reread config, enable and start service cockpit.socket
      systemd:
        name: cockpit.socket
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Update packages
      package:
        name: '*'
        state: latest
