# BEGIN ANSIBLE MANAGED BLOCK
---
# Install a role from the Ansible Galaxy
#- src: joschro.rpmfusion
#- src: joschro.rpmfusion-tainted
#- src: joschro.libvirtd
#- src: joschro.cockpit
- src: linux-system-roles.cockpit
- src: linux-system-roles.firewall
- src: linux-system-roles.certificate
  # https://github.com/debops-contrib/ansible-btrfs/blob/master/tasks/main.yml

# Install a role from GitHub
- src: https://github.com/joschro/ansible-role-rpmfusion
  name: joschro.rpmfusion
    #- src: https://github.com/joschro/ansible-role-rpmfusion-tainted
    #  name: joschro.rpmfusion-tainted
- src: https://github.com/joschro/ansible-role-libvirtd
  name: joschro.libvirtd
- src: https://github.com/joschro/ansible-role-cockpit
  name: joschro.cockpit
# Install a collection from Ansible galaxy
#collections:
#  - name: community.libvirt
# END ANSIBLE MANAGED BLOCK
